### ISSUE TITLE
When you click on the selected trail, it should populate the center card with the selected trail information.

### ISSUE THREAD

**Issue by Nmenotti20** [Jruuuu/ProjectBeen#36]

**Comment by Nmenotti20** [comment]
Information to populate in card:

1. Image of the trail.
2. Trail Name
3. Length of Trail in Tenths of a Mile.
4. Difficulty of Trail Icon (Will need to put a legend for the trail difficulty somewhere on the page).

**Comment by Jruuuu** [comment]
completed, enrique will push final edits
